upload_max_filesize = 20M
post_max_size = 20M
memory_limit = 512M
max_execution_time = 300

display_errors = Off
log_errors = On
error_log = /var/log/php-error.log

date.timezone = UTC

expose_php = Off
